csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParser.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParserRulesSpec.scala
* Switch to PackratParser where possible
* Closes https://github.com/digital-preservation/csv-validator/issues/72
=> Improve parsing performance

csv-validator-cmd/src/test/resources/uk/gov/nationalarchives/csv/validator/cmd/schema.csvs, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/Util.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/api/CsvValidator.scala, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/bigSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/caseSensitiveFilesChecksum.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/dp/regexRuleSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/duplicateColumnIdsMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/fileExistsCrossRefSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/fileExistsSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/ignoreCaseSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/regexRulePassMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/regexRuleSchemaWithoutNoHeaderSet.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/twoRuleSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/api/schema.csvs, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidatorAcceptanceSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidatorSpec.scala
This feature validates the column header in the csv file against the column name define in the schema
=> [feature]  Check column header

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/Util.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/api/CsvValidator.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/UtilSpec.scala
Improved the error message on the column header validation,
Display the inconsistent columns disregarding of whether they are defined into the schema or they are actual column header.
=> [feature] Improved the error message on the column header validation

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParser.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/package.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/CaseRuleSpec.scala
Create uppercase and lowercase rule to enforce all the characters of a column to be in a specific case.
=> Feature enforce column case

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParser.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/package.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/CaseRuleSpec.scala
Implemented case column enforcement
=> [feature] Implemented Column Case enforcement

csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/CsvValidatorUi.scala
Set exitOnClose flag on main window to properly terminate.
=> [bugfix] Exit on close.

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/AllErrorsMetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/FailFastMetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/Util.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/api/CsvValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Schema.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParser.scala, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/integrityCheck/WO_95/tech_acq_metadata_v1_WO95Y14B000.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/integrityCheck/header/integrityCheckDefaultIncludeFolderSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/integrityCheck/header/integrityCheckSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/integrityCheck/noheader/badIntegrityCheckSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/integrityCheck/noheader/integrityCheckSchema.csvs, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidatorIntegrityCheckSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/IntegrityCheckRuleSpec.scala
The integrity check is now a column rule instead of a directive.
=> [feature] Refactored integrity check to Column rule

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParser.scala, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/ifElseRuleSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/ifRuleFailElseMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/ifRuleFailThenMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/ifRulePassMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/ifRuleSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/switch1RuleFailMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/switch1RulePassMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/switch1RuleSchema.csvs, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/switch2RuleFailMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/switch2RulePassMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/switch2RuleSchema.csvs, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidatorAcceptanceSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/UtilSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/IfRuleSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/SwitchRuleSpec.scala
Switch rule as discussed at [issue #50](https://github.com/digital-preservation/csv-validator/issues/50)
=> [feature] Implemented Switch Rule

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/SchemaParser.scala, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/anyRuleFailMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/anyRulePassMetaData.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/anyRuleSchema.csvs, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidatorAcceptanceSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/UtilSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/AnyRuleSpec.scala
Implementation of the feature any as described at [#19](https://github.com/digital-preservation/csv-validator/issues/19)
=> [feature] Implemented any rule

csv-validator-parent/pom.xml
Default SCM tag and use same version for submodule.
=> Added settings for maven release plugin

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/AllErrorsMetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/Schema.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_0/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_0/SchemaParser.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_0/SchemaValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_1/Rule.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_1/SchemaParser.scala, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/notempty.csv, csv-validator-core/src/test/resources/uk/gov/nationalarchives/csv/validator/acceptance/notempty.csvs, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidatorAcceptanceSpec.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/UtilSpec.scala
Fixed [#114][bug]
[bug]: https://github.com/digital-preservation/csv-validator/issues/114
=> Bugfix notempty

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_0/SchemaParser.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_1/SchemaParser.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/NotEmptyBugTest.scala
Because rule is NOT immutable, we need to create every time newinstance.
Current code create only one, and this same instance was modified more
than 2 times.
=> [bufgix] Fix notEmpty bug plus some other related bugs.

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidator.scala
This code should have been removed in the re-factoring of the integrity check (commit 1aaa569310d16e9ae752586090f248698203f49c)
=> [bugfix] removed unused code

csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/MetaDataValidator.scala, csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/schema/v1_0/SchemaValidator.scala, csv-validator-core/src/test/scala/uk/gov/nationalarchives/csv/validator/schema/v1_0/SchemaParserColumnDefinitionsSpecs.scala
Pull request for schema-1.1 branch. This code should have been removed in the re-factoring of the integrity check (commit 1aaa569)
=> [bugfix] remove unused code

csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/CsvValidatorUi.scala
Closes https://github.com/digital-preservation/csv-validator/issues/139
=> UI should write report file in UTF-8 format

csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/CsvValidatorUi.scala, csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/ScalaSwingHelpers.scala
Closes https://github.com/digital-preservation/csv-validator/issues/331
=> Correct Save Dialog in UI

csv-validator-parent/pom.xml
Adds myself as a developer into the parent POM so sonatype can see I should be allowed to push artifacts up to maven central.
=> Add Luke Tebbs to parent POM

.github/workflows/ci.yml, csv-validator-cmd/pom.xml, csv-validator-core/pom.xml, csv-validator-java-api/pom.xml, csv-validator-parent/pom.xml, csv-validator-ui/pom.xml
Closes https://github.com/digital-preservation/csv-validator/issues/417
=> Update some dependencies and build plugins. 

csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/CsvValidatorUi.scala
Two changes, each a single line to make the user experience slightly better
=> Applied extension filter on file chooser to make it user friendly

csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/CsvValidatorUi.scala, csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/ScalaSwingHelpers.scala
Some explanations for the changes are given inline
=> Bug 453 result pane goes blank

csv-validator-distribution/assembly-windows-with-jre.xml, csv-validator-distribution/pom.xml
Using 64 bit JRE for the bundled version
=> Modifications to bundle 64 bit JRE so users can more heap memory

csv-validator-ui/src/main/scala/uk/gov/nationalarchives/csv/validator/ui/CsvValidatorUi.scala
Even though we have the drag and drop, now, it's still a good idea to add this, as:
1. There will be people that would not read the release notes/documentation
2. There will be people who prefer the file picker
3. There will be people who might find dragging and dropping physically difficult
=> Default to the last picked folder location

csv-validator-cmd/pom.xml, csv-validator-core/pom.xml, csv-validator-distribution/pom.xml, csv-validator-java-api/pom.xml, csv-validator-parent/pom.xml, csv-validator-ui/pom.xml, pom.xml
PR to get the release branch changes into master
=> 1.4.x release branch
